// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7UozsNIzXHv6xULmDGhDV7yF81I_Xzmc',
    appId: '1:343092277698:web:51a74aba43ce77fcefa65b',
    messagingSenderId: '343092277698',
    projectId: 'reservation-service-a4ace',
    authDomain: 'reservation-service-a4ace.firebaseapp.com',
    storageBucket: 'reservation-service-a4ace.firebasestorage.app',
    measurementId: 'G-FPDX4KRG20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9QfBeIMoN3Nh3OBbvuH8tjShwcC72gdU',
    appId: '1:343092277698:android:0dfb206781ad90d8efa65b',
    messagingSenderId: '343092277698',
    projectId: 'reservation-service-a4ace',
    storageBucket: 'reservation-service-a4ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHQFLSsRiwQ4SMoZ6khzn7b9oGuv10ibk',
    appId: '1:343092277698:ios:adcf87bfc21fed6befa65b',
    messagingSenderId: '343092277698',
    projectId: 'reservation-service-a4ace',
    storageBucket: 'reservation-service-a4ace.firebasestorage.app',
    iosBundleId: 'com.example.reservationServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHQFLSsRiwQ4SMoZ6khzn7b9oGuv10ibk',
    appId: '1:343092277698:ios:adcf87bfc21fed6befa65b',
    messagingSenderId: '343092277698',
    projectId: 'reservation-service-a4ace',
    storageBucket: 'reservation-service-a4ace.firebasestorage.app',
    iosBundleId: 'com.example.reservationServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7UozsNIzXHv6xULmDGhDV7yF81I_Xzmc',
    appId: '1:343092277698:web:32b382b21c6eebfaefa65b',
    messagingSenderId: '343092277698',
    projectId: 'reservation-service-a4ace',
    authDomain: 'reservation-service-a4ace.firebaseapp.com',
    storageBucket: 'reservation-service-a4ace.firebasestorage.app',
    measurementId: 'G-HQ9BHPHH1M',
  );

}